# Generated by Django 4.2.7 on 2023-12-01 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_deleted", models.DateTimeField(default=None, null=True)),
                ("name", models.CharField(max_length=300)),
                ("is_qualified", models.BooleanField(default=False)),
                ("data_privacy", models.BooleanField(default=False)),
                ("capsule_proposal", models.FileField(upload_to="capsule_proposals")),
                ("links", models.TextField(blank=True, null=True)),
                ("group_name", models.CharField(max_length=100)),
                ("member_1_name", models.CharField(max_length=100)),
                (
                    "member_1_number",
                    models.CharField(default=None, max_length=20, null=True),
                ),
                ("member_1_email", models.EmailField(max_length=254)),
                (
                    "university_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("eligibility", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="startups",
                        to="users.startupuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StartupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_deleted", models.DateTimeField(default=None, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="startups.startup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="startup_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReadinessLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_deleted", models.DateTimeField(default=None, null=True)),
                ("trl", models.IntegerField(default=0)),
                ("orl", models.IntegerField(default=0)),
                ("mrl", models.IntegerField(default=0)),
                ("rrl", models.IntegerField(default=0)),
                ("arl", models.IntegerField(default=0)),
                ("irl", models.IntegerField(default=0)),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness_levels",
                        to="startups.startup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
