# Generated by Django 4.2.7 on 2023-11-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_deleted", models.DateTimeField(default=None, null=True)),
                ("data_privacy", models.BooleanField()),
                ("starup_name", models.CharField(max_length=300)),
                ("capsule_proposal", models.FileField(upload_to="capsule_proposals")),
                ("links", models.TextField(blank=True, null=True)),
                ("group_name", models.CharField(max_length=100)),
                ("member_1_name", models.CharField(max_length=100)),
                ("member_1_number", models.CharField(max_length=20)),
                ("member_1_email", models.EmailField(max_length=254)),
                ("member_2_name", models.CharField(max_length=100)),
                ("member_3_name", models.CharField(max_length=100)),
                ("member_4_name", models.CharField(max_length=100)),
                ("member_5_name", models.CharField(max_length=100)),
                ("university_name", models.CharField(max_length=200)),
                ("eligibility", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_deleted", models.DateTimeField(default=None, null=True)),
                ("name", models.CharField(max_length=300)),
                (
                    "applicant",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="startup",
                        to="startups.applicant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="startup",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReadinessLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_deleted", models.DateTimeField(default=None, null=True)),
                ("trl", models.IntegerField(default=0)),
                ("orl", models.IntegerField(default=0)),
                ("mrl", models.IntegerField(default=0)),
                ("rrl", models.IntegerField(default=0)),
                ("arl", models.IntegerField(default=0)),
                ("irl", models.IntegerField(default=0)),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness_levels",
                        to="startups.startup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
