# Generated by Django 4.2.7 on 2023-12-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("startups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitialReadinessLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_deleted", models.DateTimeField(default=None, null=True)),
                ("trl", models.CharField(max_length=10)),
                ("orl", models.CharField(max_length=10)),
                ("mrl", models.CharField(max_length=10)),
                ("rrl", models.CharField(max_length=10)),
                ("arl", models.CharField(max_length=10)),
                ("irl", models.CharField(max_length=10)),
                (
                    "startup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_readiness_level",
                        to="startups.startup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
