# Generated by Django 4.2.7 on 2023-11-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="member_4_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="member_5_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="university_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
