# Generated by Django 4.2.7 on 2023-12-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startups", "0002_initialreadinesslevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="initialreadinesslevel",
            name="arl_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="initialreadinesslevel",
            name="irl_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="initialreadinesslevel",
            name="mrl_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="initialreadinesslevel",
            name="orl_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="initialreadinesslevel",
            name="rrl_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="initialreadinesslevel",
            name="trl_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="initialreadinesslevel",
            name="arl",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="initialreadinesslevel",
            name="irl",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="initialreadinesslevel",
            name="mrl",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="initialreadinesslevel",
            name="orl",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="initialreadinesslevel",
            name="rrl",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="initialreadinesslevel",
            name="trl",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
