# Generated by Django 4.2.7 on 2023-12-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_mentoruser_alter_baseuser_user_type"),
        (
            "startups",
            "0004_readinesslevelcriterionanswer_startupreadinesslevel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="startup",
            name="mentors",
            field=models.ManyToManyField(
                related_name="startups", to="users.mentoruser"
            ),
        ),
    ]
