# Generated by Django 4.2.7 on 2024-01-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_startup_mentors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uratquestionanswer',
            old_name='respone',
            new_name='response',
        ),
    ]
