# Generated by Django 4.2.7 on 2024-01-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_rename_respone_uratquestionanswer_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uratquestionanswer',
            name='score',
            field=models.SmallIntegerField(default=1),
        ),
    ]
