# Generated by Django 4.2.7 on 2024-01-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0010_alter_technologycalculator_competitive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologycalculator',
            old_name='startup_id',
            new_name='startup',
        ),
    ]
