# Generated by Django 4.2.7 on 2024-01-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "readinesslevel",
            "0006_calculatorcategory_alter_readinesstype_rl_type_and_more",
        ),
        ("startups", "0012_delete_technologycalculator"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="readinesslevelcriterionanswer",
            unique_together={("startup", "criterion")},
        ),
        migrations.AlterUniqueTogether(
            name="uratquestionanswer",
            unique_together={("startup", "urat_question")},
        ),
        migrations.CreateModel(
            name="CalculatorQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_deleted", models.DateTimeField(default=None, null=True)),
                (
                    "calculator_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="readinesslevel.calculatorquestion",
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculator_answers_answers",
                        to="startups.startup",
                    ),
                ),
            ],
            options={
                "unique_together": {("startup", "calculator_question")},
            },
        ),
    ]
