# Generated by Django 4.2.7 on 2024-01-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readinesslevel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelcriterion',
            name='excellent_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='levelcriterion',
            name='fair_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='levelcriterion',
            name='good_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='levelcriterion',
            name='poor_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='levelcriterion',
            name='very_poor_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='readinesslevel',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scoringguide',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
