# Generated by Django 4.2.7 on 2024-01-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readinesslevel', '0004_alter_scoringguide_readiness_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringguide',
            name='description',
            field=models.CharField(max_length=700),
        ),
    ]
